name: Every minute
on:
  schedule:
    # Runs every day at 2 AM UTC
    - cron: '* * * * *'

env:
  API_KEY: ${{ secrets.PUSHOVER_API_TOKEN }}
  USER_TOKEN: ${{ secrets.PUSHOVER_USER_TOKEN }}

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API
        run: |
          echo "Triggering API..."
          curl -s \
          --form-string "token=$API_KEY" \
          --form-string "user=$USER_TOKEN" \
          --form-string "message=Yoo! wasssup, just checking in"\
          --form-string "html=1" \
          --form-string "title=Funzilla Update" \
          https://api.pushover.net/1/messages.json
